tasks:
  - name: Run Ozone FOSS
    before: sudo apt-get update && sudo apt-get install -y gettext-base && sudo rm -rf /var/lib/apt/lists/*
    init: scripts/mvnw clean package
    command: source target/go-to-scripts-dir.sh && ./start-demo-with-sso.sh
ports:
  - name: OpenMRS
    description: OpenMRS 3
    port: 80
    onOpen: open-browser
  - name: Odoo
    description: Odoo
    port: 8069
  - name: SENAITE
    description: SENAITE
    port: 8081
  - name: Keycloak
    description: Keycloak
    port: 8084
