slice_name: Average age at visit per month
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 7__table
  viz_type: echarts_timeseries_line
  x_axis: date_started
  time_grain_sqla: P1M
  xAxisForceCategorical: false
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: patient_age_at_visit
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 163
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(patient_age_at_visit)
    optionName: metric_jq19w23zmz_035vhhmdm3te
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: date_started
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: d3Category10
  seriesType: line
  show_value: false
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 1
query_context: null
cache_timeout: null
uuid: bd23b1a5-02a9-419d-9b7b-121b1ec8f9a9
version: 1.0.0
dataset_uuid: fefa8b10-bdf1-47b9-b081-89003c5e0583
