slice_name: Distribution of genders
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 2__table
  viz_type: pie
  slice_id: 3
  groupby:
  - gender
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_wdx4rv5te2k_ivtdatoui0m
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: date_created
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: false
  legendType: scroll
  legendOrientation: top
  legendMargin: null
  label_type: key_value
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  label_line: true
  show_total: true
  outerRadius: 75
  donut: true
  innerRadius: 51
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: a74a595b-3f1c-449a-8535-a5c24cb1d464
version: 1.0.0
dataset_uuid: 34e209b6-fc04-4787-a892-9fd90fcf9bb3
