slice_name: Total sales today
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 5__table
  viz_type: big_number
  slice_id: 11
  x_axis: line_creation_date
  time_grain_sqla: P1D
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: subtotal
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 117
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(subtotal)
    optionName: metric_qn4vn0ixx3l_3cwiqluskqz
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: line_creation_date
  show_timestamp: true
  show_trend_line: true
  start_y_axis_at_zero: true
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  currency_format:
    symbol: USD
    symbolPosition: prefix
  time_format: smart_date
  force_timestamp_formatting: false
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[{"col":"line_creation_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"line_creation_date","label":"line_creation_date","expressionType":"SQL"}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"subtotal","description":null,"expression":null,"filterable":true,"groupby":true,"id":117,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(subtotal)","optionName":"metric_qn4vn0ixx3l_3cwiqluskqz","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"pivot","options":{"index":["line_creation_date"],"columns":[],"aggregates":{"SUM(subtotal)":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"5__table","viz_type":"big_number","slice_id":11,"x_axis":"line_creation_date","time_grain_sqla":"P1D","metric":{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"subtotal","description":null,"expression":null,"filterable":true,"groupby":true,"id":117,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(subtotal)","optionName":"metric_qn4vn0ixx3l_3cwiqluskqz","sqlExpression":null},"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"line_creation_date"}],"show_timestamp":true,"show_trend_line":true,"start_y_axis_at_zero":true,"color_picker":{"a":1,"b":135,"g":122,"r":0},"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","currency_format":{"symbol":"USD","symbolPosition":"prefix"},"time_format":"smart_date","force_timestamp_formatting":false,"rolling_type":"None","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 24361f4d-b7d6-4577-9e50-7afa8be82e6c
version: 1.0.0
dataset_uuid: ca368613-61d0-47ec-a2ec-0e32d0fc2d51
