name=Ozone with distro.properties sample project
version=3.7.1
war.openmrs=2.8.8
omod.initializer=2.12.0
omod.fhir2=4.2.0
omod.webservices.rest=3.5.0
omod.idgen=5.0.4
omod.legacyui=2.1.0
omod.addresshierarchy=2.21.0
omod.patientdocuments=1.1.0
omod.metadatamapping=2.0.0
omod.openconceptlab=3.1.0
omod.referencedemodata=2.6.1
omod.attachments=4.0.0
omod.queue=3.0.0
omod.appointments=2.1.0
omod.appointments.groupId=org.bahmni.module
omod.teleconsultation=2.0.0
omod.teleconsultation.groupId=org.bahmni.module
omod.cohort=3.7.3
omod.reporting=2.1.0
omod.reportingrest=2.0.0
omod.calculation=2.0.0
omod.htmlwidgets=2.0.1
omod.serialization.xstream=0.3.0
omod.serialization.xstream.type=omod
omod.ordertemplates=2.2.0
omod.patientflags=3.0.10
omod.o3forms=2.3.0
omod.authentication=2.3.0
omod.emrapi=3.4.0
omod.event.groupId=org.openmrs
omod.event=4.0.0
omod.bedmanagement=7.2.0
omod.stockmanagement=3.0.0
omod.billing=2.3.0
omod.tasks=2.1.0
content.referenceapplication=1.4.0
content.referenceapplication-demo=1.9.2
