port: 7880
bind_addresses:
  - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
redis:
  address: redis:6379
  password: password
keys:
  ozoneAdmin: 19d2de15-f7ef-44a2-abd3-a2c59a825bd2
turn:
  enabled: false
  domain: localhost
  tls_port: 5349
  udp_port: 3478
  external_tls: true
logging:
  level: info
