name: Build, validate and optionally publish (if pushed on main)

on:
  pull_request:
    branches: [main]
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"

      - name: Build and Validate
        run: mvn --batch-mode --update-snapshots --activate-profiles validator clean package

      - name: Set settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [
            {
              "id": "mks-nexus-public-releases",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            },
            {
              "id": "mks-nexus-public-snapshots",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Publish
        run: mvn --batch-mode clean deploy
        if: ${{ github.ref == 'refs/heads/main' }}
